# Generated by Django 2.2.17 on 2023-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_submission_started_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='docker_image',
            field=models.CharField(default='aimultimedialab/ai4mediabench-default-py39:latest', max_length=128),
        ),
    ]
