# Generated by Django 2.2.17 on 2023-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_merge_20230906_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='docker_image',
            field=models.CharField(default='codalab/codalab-legacy:py37', max_length=128),
        ),
        migrations.AlterField(
            model_name='phase',
            name='has_max_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
